// Starter cards, built from the project's starter-card files.
// This seeds the shared board the first time it's opened.
export const RAW_SEED = [
  // ---- Chill / Food & Coffee ----
  {title:"Coffee shop hangout", category:"Food / Coffee", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"This Week",
   description:"Drinks somewhere with good seats. No plan, no reason needed.",
   starterVersion:"Grab drinks and stay 20 minutes. If it's nice, stay longer.", goal:"Easy time to just talk.",
},
  {title:"Food crawl", category:"Food / Coffee", timeEstimate:"2 hours", costLevel:"Moderate", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"A few small stops instead of one big meal. One bite each.",
   starterVersion:"Pick two spots, one snack at each, walk between them."},
  {title:"Just talk drive", category:"Chill", timeEstimate:"30 minutes", costLevel:"Cheap", energyLevel:"Low", location:"Car", appealTo:"Everyone", status:"Ideas",
   description:"No destination. Windows down, someone picks the music.",
   starterVersion:"Drive 15 minutes with a good playlist, then head back."},
  {title:"Movie night with a theme", category:"Chill", timeEstimate:"2 hours", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Pick a loose theme (bad 90s action, heist movies, whatever).",
   starterVersion:"Each person names one movie, pick by coin flip."},
  {title:"Used bookstore visit", category:"Chill", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Wander the aisles, no shopping list.",
   starterVersion:"Everyone finds one book under $5 to show the others."},
  {title:"Record / vintage shop visit", category:"Music / Culture", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Dig through crates and shelves. No need to buy.",
   starterVersion:"Find one album cover you love and one you can't stand."},
  {title:"Walk and talk", category:"Chill", timeEstimate:"30 minutes", costLevel:"Free", energyLevel:"Medium", location:"Neighborhood", appealTo:"Everyone", status:"Ideas",
   description:"A loop around the block, no phones.",
   starterVersion:"One lap after dinner. That's it."},
  {title:"Library visit", category:"Chill", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Quiet, free, and there's always something odd to find.",
   starterVersion:"Everyone grabs one thing that looks interesting."},

  // ---- Video games ----
  {title:"Video game night", category:"Video Games", timeEstimate:"2 hours", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest + Randy", status:"Ideas",
   description:"Whatever's already on the shelf. Low stakes.",
   starterVersion:"Play one match of a game someone already owns."},
  {title:"Co-op video game night", category:"Video Games", timeEstimate:"2 hours", costLevel:"Cheap", energyLevel:"Medium", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"On the same team instead of against each other.",
   starterVersion:"Pick one co-op game and beat a single level together."},
  {title:"Retro game night", category:"Video Games", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Randy + Forrest", status:"Ideas",
   description:"The old stuff Dad grew up on.",
   starterVersion:"Load one game Dad played as a kid and hand over a controller."},
  {title:"Try a game one person loves", category:"Video Games", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Let one person be the guide for once.",
   starterVersion:"One person teaches their favorite for 20 minutes, no judging."},
  {title:"Build a video game idea", category:"Creative", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest", status:"Ideas",
   description:"Not building the game — just dreaming it up on paper.",
   starterVersion:"Sketch one character and one level on paper."},
  {title:"Arcade night", category:"Games", timeEstimate:"2 hours", costLevel:"Moderate", energyLevel:"Medium", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Loud, bright, and easy.",
   starterVersion:"$10 in tokens each, meet back in 30 minutes."},

  // ---- Board & card games ----
  {title:"Family board game night", category:"Board Games", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"This Week",
   description:"Casual, not a tournament. Unless it turns into one.",
   starterVersion:"Pick the shortest game on the shelf.",
},
  {title:"Chess night", category:"Board Games", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Randy + Forrest", status:"Ideas",
   description:"Slow game, good conversation.",
   starterVersion:"Play one game, no clock, take-backs allowed."},
  {title:"Poker night", category:"Card Games", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Chips or candy, never real money.",
   starterVersion:"Deal a few hands for a bowl of snacks."},
  {title:"Board game cafe visit", category:"Board Games", timeEstimate:"2 hours", costLevel:"Moderate", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"A wall of games and someone to explain them.",
   starterVersion:"Try one game the staff recommends."},
  {title:"Thrifted board game gamble", category:"Board Games", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Buy a random cheap game and risk it.",
   starterVersion:"Grab one $3 game and play it tonight, missing pieces and all."},
  {title:"Puzzle night", category:"Chill", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Background music, snacks, no finish line.",
   starterVersion:"Start a 500-piece puzzle. No pressure to finish it."},

  // ---- Creative ----
  {title:"Painting session", category:"Creative", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Cheap paint, no talent required.",
   starterVersion:"Everyone paints the same object for 20 minutes, then compare."},
  {title:"Model kit building", category:"Creative", timeEstimate:"2 hours", costLevel:"Moderate", energyLevel:"Low", location:"Home", appealTo:"Randy + Forrest", status:"Ideas",
   description:"A car, a plane, a robot — something to build together.",
   starterVersion:"Open one kit and build just the first step together."},
  {title:"Hot Wheels photo shoot", category:"Creative", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest", status:"Ideas",
   description:"Make tiny cars look huge.",
   starterVersion:"Set up three cars and take five cool photos."},
  {title:"Make a family logo or sticker", category:"Creative", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"A dumb little mascot for the family.",
   starterVersion:"Each person doodles one version in 10 minutes."},
  {title:"Build a tiny fantasy map", category:"Creative", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Pearl + Everyone", status:"Ideas",
   description:"Invent a place and name everything in it.",
   starterVersion:"Draw one island and name three spots on it."},

  // ---- Collecting ----
  {title:"Fossil hunting", category:"Collecting", timeEstimate:"Half day", costLevel:"Cheap", energyLevel:"Medium", location:"North Georgia", appealTo:"Everyone", status:"Someday",
   description:"Creek beds and road cuts hide real fossils.",
   starterVersion:"Watch one video on where to look, then pick a spot."},
  {title:"Metal detecting", category:"Collecting", timeEstimate:"2 hours", costLevel:"Moderate", energyLevel:"Medium", location:"Local", appealTo:"Randy + Forrest", status:"Ideas",
   description:"Beep, dig, mostly bottle caps — occasionally treasure.",
   starterVersion:"Borrow or rent a detector and sweep the backyard first."},
  {title:"Hot Wheels hunt", category:"Collecting", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Local", appealTo:"Forrest", status:"Ideas",
   description:"The thrill is finding the good one before anyone else.",
   starterVersion:"Hit one store's toy aisle and look for a Treasure Hunt car."},
  {title:"Sports card value challenge", category:"Collecting", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Forrest", status:"Ideas",
   description:"Guess first, then look it up.",
   starterVersion:"Each pick one card, guess its value, then check online."},
  {title:"Rock and mineral sorting", category:"Collecting", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Weirdly relaxing.",
   starterVersion:"Sort a box by color for 20 minutes."},

  // ---- Make money ----
  {title:"$20 thrift flip", category:"Make Money", timeEstimate:"2 hours", costLevel:"Cheap", energyLevel:"Medium", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Find something cheap that's worth more than it looks.",
   starterVersion:"Spend up to $20, find one thing you could resell."},
  {title:"eBay flipping challenge", category:"Make Money", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest", status:"Ideas",
   description:"Turn clutter into a little cash.",
   starterVersion:"List one thing from around the house today."},
  {title:"Sell one thing challenge", category:"Make Money", timeEstimate:"30 minutes", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Small win, real money.",
   starterVersion:"Photograph and price one item to sell."},
  {title:"Mini business brainstorm", category:"Make Money", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest + Pearl", status:"Ideas",
   description:"No bad ideas allowed, just quantity.",
   starterVersion:"Write down five tiny business ideas without filtering."},

  // ---- Sports / movement ----
  {title:"Golf cart ride while Dad plays", category:"Sports", timeEstimate:"Half day", costLevel:"Moderate", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"You don't have to play to come along.",
   starterVersion:"Ride along for 9 holes, then get lunch after."},
  {title:"Driving range", category:"Sports", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Medium", location:"Local", appealTo:"Everyone", status:"This Week",
   description:"Hit balls, no rules, no scorecard.",
   starterVersion:"Split one bucket of balls between everyone."},
  {title:"Mini golf", category:"Sports", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Local", appealTo:"Everyone", status:"Done",
   description:"Windmills and questionable putting.",
   starterVersion:"Play the front nine only."},
  {title:"Topgolf", category:"Sports", timeEstimate:"2 hours", costLevel:"Moderate", energyLevel:"Medium", location:"Local", appealTo:"Everyone", status:"This Month",
   description:"Golf but easy and social.",
   starterVersion:"Share one bay for an hour."},
  {title:"Bowling", category:"Sports", timeEstimate:"1 hour", costLevel:"Moderate", energyLevel:"Medium", location:"Local", appealTo:"Everyone", status:"Ideas",
   description:"Bumpers allowed, dignity optional.",
   starterVersion:"One game. Loser buys the snacks."},
  {title:"Stone Mountain walk", category:"Adventure", timeEstimate:"Half day", costLevel:"Cheap", energyLevel:"Medium", location:"Stone Mountain", appealTo:"Everyone", status:"Ideas",
   description:"Big views without needing to be an athlete.",
   starterVersion:"Walk the easy base trail and skip the summit."},
  {title:"Disc golf", category:"Sports", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Medium", location:"Local", appealTo:"Randy + Forrest", status:"Ideas",
   description:"Free courses everywhere, low barrier.",
   starterVersion:"Play the first three holes at a free course."},

  // ---- Life skill / future ----
  {title:"Driving lesson practice", category:"Life Skill", timeEstimate:"30 minutes", costLevel:"Free", energyLevel:"Low", location:"Local", appealTo:"Forrest + Pearl", status:"Ideas",
   description:"Low-stakes practice, no traffic.",
   starterVersion:"15 minutes in an empty parking lot."},
  {title:"Cooking one meal", category:"Life Skill", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"One meal, split the jobs.",
   starterVersion:"Pick one simple recipe and each take a step."},
  {title:"College visit", category:"Future / College", timeEstimate:"Full day", costLevel:"Moderate", energyLevel:"Low", location:"Varies", appealTo:"Forrest + Pearl", status:"Someday",
   description:"No pressure, just a look around.",
   starterVersion:"Look up one nearby campus and plan a walk-through."},
  {title:"Car basics", category:"Life Skill", timeEstimate:"30 minutes", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest", status:"Ideas",
   description:"The stuff every driver should know.",
   starterVersion:"Learn to check oil and tire pressure."},
  {title:"Budgeting basics", category:"Life Skill", timeEstimate:"30 minutes", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Forrest + Pearl", status:"Ideas",
   description:"Where does the money actually go?",
   starterVersion:"Map one week of spending together."},

  // ---- Travel / big dream ----
  {title:"NYC trip", category:"Travel", timeEstimate:"Big trip", costLevel:"Expensive", energyLevel:"Medium", location:"New York", appealTo:"Everyone", status:"Someday",
   description:"The big one. Someday, maybe.",
   starterVersion:"Each person saves one place they'd want to see."},
  {title:"Grand Canyon trip", category:"Big Dream", timeEstimate:"Big trip", costLevel:"Big trip", energyLevel:"Medium", location:"Arizona", appealTo:"Everyone", status:"Someday",
   description:"A real bucket-list one, kept alive here.",
   starterVersion:"Watch one 10-minute video, each save one spot to see."},
  {title:"Weekend mountain trip", category:"Travel", timeEstimate:"Weekend", costLevel:"Moderate", energyLevel:"Medium", location:"North Georgia", appealTo:"Everyone", status:"Someday",
   description:"A cabin and no schedule.",
   starterVersion:"Pick one weekend and one cabin to look at."},
  {title:"Beach shark tooth trip", category:"Travel", timeEstimate:"Weekend", costLevel:"Moderate", energyLevel:"Medium", location:"Coast", appealTo:"Everyone", status:"Someday",
   description:"Treasure hunting at the shoreline.",
   starterVersion:"Watch one video on where teeth wash up, then pick a beach."},

  // ---- House / organizing ----
  {title:"Treasure box cleanout", category:"House / Organizing", timeEstimate:"30 minutes", costLevel:"Free", energyLevel:"Low", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"One box at a time. Find forgotten stuff.",
   starterVersion:"Pick one box, 25 minutes, keep / sell / donate piles."},
  {title:"Collection display", category:"House / Organizing", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Low", location:"Home", appealTo:"Forrest", status:"Ideas",
   description:"Show off the good stuff instead of boxing it.",
   starterVersion:"Display your best 10 items on one shelf."},
  {title:"Studio cleanup with reward", category:"House / Organizing", timeEstimate:"1 hour", costLevel:"Cheap", energyLevel:"Medium", location:"Home", appealTo:"Everyone", status:"Ideas",
   description:"Short burst, then a treat.",
   starterVersion:"25 minutes of cleanup, then go get a treat."},

  // ---- Local Atlanta ----
  {title:"Atlanta BeltLine walk and food stop", category:"Local Atlanta", timeEstimate:"2 hours", costLevel:"Cheap", energyLevel:"Medium", location:"Atlanta", appealTo:"Everyone", status:"Ideas",
   description:"Walk a stretch, eat something, people-watch.",
   starterVersion:"Walk one section and stop for one snack."},
  {title:"Ponce City Market / Skyline Park", category:"Local Atlanta", timeEstimate:"Half day", costLevel:"Moderate", energyLevel:"Medium", location:"Atlanta", appealTo:"Everyone", status:"Ideas",
   description:"Rooftop carnival games and a food hall.",
   starterVersion:"Ride two rides at Skyline Park, then grab food downstairs."},
  {title:"Fernbank Museum", category:"Local Atlanta", timeEstimate:"Half day", costLevel:"Moderate", energyLevel:"Low", location:"Atlanta", appealTo:"Everyone", status:"Ideas",
   description:"Giant dinosaurs and a nature walk.",
   starterVersion:"See the dinosaurs first, skip the rest if you're tired."},
  {title:"Georgia Aquarium", category:"Local Atlanta", timeEstimate:"Half day", costLevel:"Expensive", energyLevel:"Low", location:"Atlanta", appealTo:"Everyone", status:"Ideas",
   description:"Whale sharks the size of a bus.",
   starterVersion:"Go straight to the whale shark tunnel first."},
  {title:"Buford Highway food adventure", category:"Local Atlanta", timeEstimate:"2 hours", costLevel:"Cheap", energyLevel:"Low", location:"Atlanta", appealTo:"Everyone", status:"This Month",
   description:"Some of the best, cheapest food in the city.",
   starterVersion:"Pick one country's food none of you have tried."},
  {title:"Oakland Cemetery photo walk", category:"Local Atlanta", timeEstimate:"1 hour", costLevel:"Free", energyLevel:"Low", location:"Atlanta", appealTo:"Everyone", status:"Ideas",
   description:"Beautiful, historic, and free.",
   starterVersion:"Everyone takes five photos, then compare favorites."},
  {title:"Little Five Points wander", category:"Local Atlanta", timeEstimate:"2 hours", costLevel:"Cheap", energyLevel:"Low", location:"Atlanta", appealTo:"Everyone", status:"Ideas",
   description:"Records, vintage, and weird shops.",
   starterVersion:"Browse one record shop and one vintage store."},
];
